export enum TipoDocumentoArchivo {

  IDENTIFICACION = 'IDENTIFICACION',

  HISTORIA_CLINICA = 'HISTORIA_CLINICA',

  AUTORIZACION = 'AUTORIZACION',

  IMAGENOLOGIA = 'IMAGENOLOGIA',

  ANEXO_2 = 'ANEXO_2',

  ANEXO_3 = 'ANEXO_3',

  FACTURA = 'FACTURA',

  OTRO = 'OTRO'

}